version: '3.1'
services:
  app:
    image: nginx:alpine
    container_name: web-rfkautopartes
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./appdata/html:/usr/share/nginx/html
